# /app/services/reporting.py
import os
import json
import hashlib
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch


def suggest_ipc_sections(scam_type: str) -> List[str]:
    """
    Automatically suggests relevant IPC and IT Act sections based on detected scam type.
    Used for FIR drafting and legal reporting.
    """
    scam_lower = scam_type.lower()

    charges = ["Section 420 IPC (Cheating and dishonestly inducing delivery of property)"]

    if any(word in scam_lower for word in ["kyc", "bank", "upi", "account", "payment"]):
        charges.extend([
            "Section 419 IPC (Cheating by personation)",
            "Section 66D IT Act, 2000 (Cheating by personation using computer resource)",
            "Section 66C IT Act, 2000 (Identity Theft)"
        ])

    if "sextortion" in scam_lower or "blackmail" in scam_lower or "extortion" in scam_lower:
        charges.extend([
            "Section 384 IPC (Punishment for extortion)",
            "Section 385 IPC (Putting person in fear of injury in order to commit extortion)",
            "Section 67A IT Act, 2000 (Publishing or transmitting of material containing sexually explicit act)"
        ])

    if any(word in scam_lower for word in ["voice", "deepfake", "ai voice", "impersonation"]):
        charges.extend([
            "Section 66E IT Act, 2000 (Violation of privacy)",
            "Section 419 IPC (Cheating by personation)",
            "Section 66D IT Act, 2000 (Cheating by personation using computer resource)"
        ])

    if "lottery" in scam_lower or "prize" in scam_lower or "investment" in scam_lower:
        charges.append("Section 420 IPC (already included) + Section 506 IPC (Criminal intimidation)")

    # Remove duplicates and sort
    return sorted(list(set(charges)))


def generate_crime_report(session_id: str, data: Dict[str, Any]) -> str:
    """
    Generates a formal, court-admissible First Information Report (FIR) draft in PDF format.
    Structured for Indian cyber-crime reporting (NCRP/NCRB compatible).
    """
    filename = f"FIR_Draft_{session_id}.pdf"
    path = os.path.join("static", filename)

    c = canvas.Canvas(path, pagesize=letter)
    width, height = letter

    # ── OFFICIAL HEADER ─────────────────────────────────────────────────────────
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width/2, height - 50, "FIRST INFORMATION REPORT (DRAFT)")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width/2, height - 65, "Generated by VIBHISHAN – AI-powered Cyber Defense System")
    c.line(50, height - 75, width - 50, height - 75)

    # ── SECTION 1: INCIDENT DETAILS ─────────────────────────────────────────────
    y = height - 100
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "1. INCIDENT DETAILS")
    y -= 25
    c.setFont("Helvetica", 10)
    c.drawString(60, y, f"Session / Case ID: {session_id}")
    c.drawString(300, y, f"Report Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}")
    y -= 20
    c.drawString(60, y, f"Detected Scam Category: {data.get('scam_type', 'Unknown').upper()}")
    c.drawString(300, y, f"Threat / Risk Score: {data.get('scam_score', 0)} / 100")
    y -= 20
    c.drawString(60, y, f"Reporting System: Vigilante-OS (Automated Engagement)")

    # ── SECTION 2: SUSPECT DIGITAL TRACE ────────────────────────────────────────
    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "2. SUSPECT IDENTIFIERS (Actionable Intelligence)")
    y -= 25
    c.setFont("Helvetica", 10)

    intel = data.get("extracted", {})
    if intel.get("upi_ids"):
        c.drawString(60, y, f"UPI Handles / VPAs: {', '.join(intel['upi_ids'])}")
        y -= 20
        if data.get("metadata", {}).get("freeze_id"):
            c.setFont("Helvetica-Bold", 10)
            c.drawString(70, y, f"KINGPIN FREEZE ID: {data['metadata']['freeze_id']} (Simulated NPCI Lock)")
            c.setFont("Helvetica", 10)
            y -= 20
    if intel.get("bank_accounts"):
        c.drawString(60, y, f"Bank Accounts / IFSC: {', '.join(intel['bank_accounts'])}")
        y -= 20
    if intel.get("phone_numbers"):
        c.drawString(60, y, f"Phone Numbers: {', '.join(intel['phone_numbers'])}")
        y -= 20
    if intel.get("urls"):
        c.drawString(60, y, f"Phishing / Payment URLs: {', '.join(intel['urls'])}")
        y -= 20

    if not (intel.get("upi_ids") or intel.get("bank_accounts") or intel.get("phone_numbers") or intel.get("urls")):
        c.drawString(60, y, "No direct identifiers captured in this session.")

    # ── SECTION 3: ADVERSARY BEHAVIORAL PROFILE ────────────────────────────────
    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "3. ADVERSARY BEHAVIORAL & PSYCHOLOGICAL PROFILE")
    y -= 25
    c.setFont("Helvetica", 10)
    c.drawString(60, y, f"Behavioral Fingerprint: {data.get('behavioral_fingerprint', 'UNKNOWN')}")
    y -= 20
    c.drawString(60, y, f"Estimated Emotional State (last): {data.get('emotion_history', ['Unknown'])[-1] if data.get('emotion_history') else 'Unknown'}")
    y -= 20
    c.drawString(60, y, f"Number of Encounters: {data.get('encounters', 1)}")

    # ── SECTION 4: RECOMMENDED LEGAL CHARGES ────────────────────────────────────
    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "4. RECOMMENDED CHARGES (Automated Legal Mapping)")
    y -= 25
    c.setFont("Helvetica", 10)

    sections = suggest_ipc_sections(data.get("scam_type", "Unknown"))
    for section in sections:
        c.drawString(60, y, f"• {section}")
        y -= 18

    # ── SECTION 5: DIGITAL EVIDENCE INTEGRITY (CHAIN OF CUSTODY) ───────────────
    y -= 30
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "5. DIGITAL EVIDENCE INTEGRITY")
    y -= 25
    c.setFont("Courier", 9)
    # Simple hash of the entire report data (for chain of custody)
    report_data_str = json.dumps(data, sort_keys=True)
    evidence_hash = hashlib.sha256(report_data_str.encode('utf-8')).hexdigest()
    c.drawString(60, y, f"SHA-256 Hash of Captured Evidence: {evidence_hash}")
    y -= 20
    c.drawString(60, y, "(This hash can be verified against original system logs)")

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 30, "Confidential – For Law Enforcement / Cyber Crime Cell Use Only")
    c.drawString(width - 150, 30, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    c.save()
    return path


def generate_ncrp_report(session_id: str, data: Dict[str, Any]) -> str:
    """
    Generates structured JSON report compatible with National Cyber Crime Reporting Portal (NCRP/NCRB).
    """
    ncrp_format = {
        "report_header": {
            "source_system": "VIGILANTE-OS",
            "report_date": datetime.now().isoformat(),
            "case_id": session_id,
            "reporting_entity": "AI-powered scam baiting & intelligence system",
            "version": "1.0"
        },
        "suspect_details": {
            "digital_fingerprint": data.get("behavioral_fingerprint", "UNKNOWN"),
            "suspect_phone": data.get("phone_number", "UNKNOWN"),
            "suspect_language": data.get("language_detected", "Unknown"),
            "confidence_score": round(data.get("scam_score", 0) / 100, 2),
            "emotion_pattern_last_3": data.get("emotion_history", [])[-3:] if data.get("emotion_history") else []
        },
        "crime_evidence": {
            "category": "FINANCIAL_FRAUD",
            "subcategory": data.get("scam_type", "Unknown").upper(),
            "incident_timestamp": datetime.now().isoformat(),
            "extracted_identifiers": {
                "bank_accounts": data.get("extracted", {}).get("bank_accounts", []),
                "upi_handles": data.get("extracted", {}).get("upi_ids", []),
                "phone_numbers": data.get("extracted", {}).get("phone_numbers", []),
                "phishing_urls": data.get("extracted", {}).get("urls", [])
            },
            "conversation_summary": {
                "total_turns": len(data.get("history_summary", [])) // 2,
                "last_tactic_used": data.get("tactic_used", "NONE"),
                "intelligence_collected": bool(data.get("extracted", {}))
            }
        },
        "ai_audit_trail": {
            "autonomous_engagement_turns": len(data.get("history_summary", [])) // 2,
            "tactic_used": data.get("tactic_used", "NONE"),
            "persona_used": data.get("persona", "Unknown"),
            "system_generated": True,
            "confidence_fusion_score": data.get("fusion_probability", 0.0)
        }
    }

    filename = f"NCRP_Report_{session_id}.json"
    path = os.path.join("static", filename)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(ncrp_format, f, indent=4, ensure_ascii=False)

    return path